force-app/main/default/objects/jcvRules__mdt/jcvRules__mdt.object-meta.xml
<CustomObject>
    <label>jcvRule</label>
    <pluralLabel>jcvRule</pluralLabel>
</CustomObject>

force-app/main/default/objects/jcvRules__mdt/fields/jsonRules__c.field-meta.xml
<CustomField>
    <fullName>jsonRules__c</fullName>
    <label>jsonRules</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/jcvRules__mdt/fields/objectName__c.field-meta.xml
<CustomField>
    <fullName>objectName__c</fullName>
    <label>objectName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/jcvRules__mdt/fields/profileName__c.field-meta.xml
<CustomField>
    <fullName>profileName__c</fullName>
    <label>profileName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/jcvRules__mdt/fields/recordTypeName__c.field-meta.xml
<CustomField>
    <fullName>recordTypeName__c</fullName>
    <label>recordTypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/jcvRules.cls
public with sharing class jcvRules {

    @AuraEnabled(cacheable=true)
    public static string getRules(String objectName, String recordTypeName) {

        Id profileId=userinfo.getProfileId();
        String rules='';
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;

        List<jcvRules__mdt> ruleList  = [select id, jsonRules__c from jcvRules__mdt where objectName__c =: objectName AND profileName__c =: profileName 
                     and recordTypeName__c =:recordTypeName limit 1] ;
        
        if(!ruleList.isEmpty())
            rules = ruleList[0].jsonRules__c;
        else
        {
            ruleList  = [select id, jsonRules__c from jcvRules__mdt where objectName__c =: objectName AND profileName__c = '*'
                     and recordTypeName__c =:recordTypeName limit 1] ;
            
            if(!ruleList.isEmpty())
                rules = ruleList[0].jsonRules__c;
        }

        return rules;


    }
}